### ISSUE TITLE
Slide Stack Not Working Properly

### ISSUE THREAD

**Issue by prohwer** [yuzoolcode/yuzoolthemes-tracking#1]
Hello - 

I am experiencing a problem with one of your stacks.

Placed a Slide Stack and referenced eight images (PNG files, but same problem with JPG files). When setting Autoplay and Slide Transition to X ms, both the Preview in RW and in Safari show hysterically changing slides at frequence of 20hz or so, looking as if overlapping the slide images.

Attached please find the zipped project which I use as a starter project to learn more about your technology and features.

I uploaded the project to a German cloud provider, you can download it here:

https://my.hidrive.com/lnk/A9giHtkk <https://my.hidrive.com/lnk/A9giHtkk>

Please have a quick look and advise, thank you!

Peter

**Comment by yuzoolcode** [comment]
Thanks for getting in touch @prohwer 

It looks like the slide interval setting needs to be `3000` without any comma or decimal

As attached

And it should work fine :) 

![2018-06-05 at 10 51](https://user-images.githubusercontent.com/4608547/40950597-6307736c-68ae-11e8-9aae-3a5a37051190.jpg)

Let me know if you still have issues

**Comment by prohwer** [comment]
My fault! Thanks for checking this and your quick and sound reply. 
This shows one thing: There ARE stupid questions..
Best - 
Peter

**Comment by yuzoolcode** [comment]
No problem! :)
