### ISSUE TITLE
Feed stack not working since jan.1

### ISSUE THREAD

**Issue by WalterBelgium** [yuzoolcode/yuzoolthemes-tracking#10]
Hello Michael
Since few days feed stack does'nt work.
Provider thinks maybe Yahoo problem (https://www.valuewalk.com/2019/01/yahoo-retires-yql-services/)
plse feedback, te Walter Merckx

**Comment by yuzoolcode** [comment]
Yes that is the issue unfortunately 
Until we can find a replacement engine that will be broken :( 

Looking for a replacement RSS parser and then will update the Stack 

Cheers

**Comment by yuzoolcode** [comment]
This has been fixed @WalterBelgium 

thanks for reporting it.

Full notes:
- Fix for broken Yahoo RSS - now this works independently and shouldn’t break again.

This is an old Stack and updates limited so for better RSS feeds and more Social links get <a href="http://selz.co/EkfZ91$YM">Wall Stack</a>

**Comment by yuzoolcode** [comment]
Sorry you feel that way - it was the best to be done in the situation and Wall supersedes this Stack so it was a quick fix.

It looks pretty good:
http://demo.yuzoolthemes.com/feed/

- You can change the date format (change YYMMDD etc) 
- What styling options did you want? It takes those from the theme with some colour overrides
- Yes title is intended to be on top ..
