### ISSUE TITLE
Routely not working

### ISSUE THREAD

**Issue by stevemutch** [yuzoolcode/yuzoolthemes-tracking#11]
Hi. Seems you need to update the Routely stack given the changes Google made to the API which now requires API key. Your demo doesn't even work.

http://demo.yuzoolthemes.com/routely/

**Comment by yuzoolcode** [comment]
Thanks for letting me know @stevemutch 

The demo is now updated (http://demo.yuzoolthemes.com/routely/shop.html)

The Stack already contains a place for the API - I just forgot to add an API key in my demo.
Republish your project with an API in the Stack as per this screen:

![rapidweaver 2019-01-27 at 22 29 54 2x](https://user-images.githubusercontent.com/4608547/51801647-f51eb000-2283-11e9-976c-83f4872ee452.jpg)

**Comment by yuzoolcode** [comment]
It was updated in Dec 2016:
https://updates.yuzoolthemes.com/post/154460220302/routely-stack-15

**Comment by yuzoolcode** [comment]
Version 1.5

I've just re-sent you your download link of 1.5 :)
