### ISSUE TITLE
Using Wall stack for RSS feed replacement, but not fully working

### ISSUE THREAD

**Issue by CaseyJRS** [yuzoolcode/yuzoolthemes-tracking#15]
The "RSS Feed JS" stack by Joe Workman no longer works due to cessation of Yahoo's API. So I purchased the Wall stack today specifically for its RSS feed capability.

I am nesting the Wall stack inside several other Stacks (i.e. the Stacks plug-in), but I see only a partial rendering of each blog entry. I've configured the Wall stack to show a maximum of 3 blog entries. The best way to illustrate the problem is to point you to the page in question:

http://www.anchorsemi.com/test

Wall stack is located in the home page of the website. By clicking the link above, you can see the 3 "partially" rendered blog entries. The link in each entry works, and you can see what each blog entry looks like by clicking each of the links.

I have **Add JQuery** checked on. If this is turned off, then nothing is displayed.

Any clues or suggestions for resolving this issue are much appreciated!

Order #YS0XWBZE

**Comment by yuzoolcode** [comment]
Thanks @CaseyJRS  -  what is your RSS URL?

> I have Add JQuery checked on. If this is turned off, then nothing is displayed.
That's fine :) 

- Some RSS feeds are not compatible by the way they are made
- Best is to put your feed into Google feed burner (http://feedburner.google.com) then back into Wall and see if that helps
- If you are wanting RSS only and these above don't work, I have another solution I can send you

**Comment by CaseyJRS** [comment]
@yuzoolcode, thanks for the prompt follow-up. Here are some of the answers:

1. The RSS URL is: http://www.anchorsemi.com/rw_common/plugins/stacks/armadillo/feed.rss
2. After copying the URL into Feed Burner, it stated that the feed was verified. I did not click the subsequent button to publish it.
3. At this time we're just using RSS for the corporate website. The Wall Stack looks lovely and we would like to use it, but we are perfectly okay with an alternative solution as well.

Thank you for your help!

**Comment by yuzoolcode** [comment]
Thanks

I just tried your feed and it is not showing a preview:
![CleanShot 2019-03-09 at 10 10 37](https://user-images.githubusercontent.com/4608547/54063967-b6e9b880-4253-11e9-84c3-234e7acede4c.jpg)

But the feed burner feed from the demo is:
https://feeds.feedburner.com/TechCrunch/social

![CleanShot 2019-03-09 at 10 11 02](https://user-images.githubusercontent.com/4608547/54063978-c2d57a80-4253-11e9-971a-44e4a03b7d1d.jpg)

It might be that Armadillo RSS is not parsing correctly. Had similar issue with that and another item.

-----

Feed Stack using the BBC RSS:
http://feeds.bbci.co.uk/news/rss.xml

![RapidWeaver 2019-03-09 at 10 12 48](https://user-images.githubusercontent.com/4608547/54063997-eef0fb80-4253-11e9-96c8-95fa9a4a920f.jpg)


Using your RSS:
![RapidWeaver 2019-03-09 at 10 13 59](https://user-images.githubusercontent.com/4608547/54064019-15169b80-4254-11e9-9392-99cdd185ac83.jpg)

**Comment by yuzoolcode** [comment]
> After copying the URL into Feed Burner, it stated that the feed was verified. I did not click the subsequent button to publish it.
> 
> At this time we're just using RSS for the corporate website. The Wall Stack looks lovely and we would like to use it, but we are perfectly okay with an alternative solution as well.

1. Please try and publish the Feedburner and place it into Wall and see how it looks
2. If it doesn't work I can send you the above Feed Stack

Cheers

**Comment by CaseyJRS** [comment]
I published the FeedBurner and placed the new URL into the Wall Stack, then published the revised website to a testing location. Unfortunately, the Wall Stack still shows empty placeholders.

I would be happy to try Feed Stack.

Thanks!

**Comment by yuzoolcode** [comment]
Sure

I can't match your profile with an email address on here... so please send me a private message (click on my profile here: https://forum.rw4all.com/c/yuzoolthemes)

And I'll send you a link for the Feed Stack :)

**Comment by CaseyJRS** [comment]
Hello Michael,

Because I don't have an account on "rw4all", are you able to look up my email address from the order I placed: Order #YS0XWBZE

If not, then I'll create an account on rw4all. Thanks!

**Comment by yuzoolcode** [comment]
That really helps - thanks - will send it today :)

**Comment by yuzoolcode** [comment]
Just sent it - will close this now :)
