### ISSUE TITLE
Stripe Stack Bug?

### ISSUE THREAD

**Issue by graham57** [yuzoolcode/yuzoolthemes-tracking#16]
Hi Michael

I have been using Stripe Stack to take occasional payments for a couple of years but over the weekend a client said she could not use it and trying it today neither could I. She successfully paid me about 3 weeks ago using it.

I do not use it that often but it is handy at times for clients to pay me.

Is it compatibility with the latest version of Rapid weaver perhaps being flash I am using 8.1.7 this month's version - perhaps definately not always a good idea!

Is there an update

page: naturalpetcare.co.uk/stripe_payment for now - its not in the menu.

Graham

**Comment by yuzoolcode** [comment]
Thanks Graham... 

This is the latest version:
https://updates.yuzoolthemes.com/post/178278823047/stripe-stack-185
But this was September last year, so not sure what has changed in the last 3 weeks.. 

As far as I can see it's working in testing still.

- Are you using 1.8.5?
- What error did you receive on the page? 
- Can you send a screenshot?

**Comment by graham57** [comment]
It was nothing to do with the stack or RW

See below I sell CBD oil for pets! I had not seen the email - No error message!

Thanks for your help guess I’ll use PayPal!

Have a good weekend
Graham

> Begin forwarded message:
> 
> From: Stripe Support <support@stripe.com>
> Subject: Your Stripe Account for naturalpetcare.co.uk
> Date: 7 March 2019 at 14:56:31 GMT
> To: "grahamhines1@icloud.com" <grahamhines1@icloud.com>
> Reply-To: Stripe Support <support@stripe.com>
> 
> 
> Hi Graham,
> 
> Thanks for using Stripe.
> 
> While we hate to give you anything less than a great experience, it does seem that your business is in violation of the Stripe Services Agreement, section A.7.b ("Restricted Businesses and Activities"). Specifically, we are unable to accept payments for cannabis and related products, including CBD as mentioned here: https://stripe.com/restricted-businesses <https://stripe.com/restricted-businesses>.
> 
> These regulations are firm, so we sadly have no flexibility with them. Unfortunately, you won’t be able to accept new charges on your account, but we will continue making payouts to your bank account until you receive all of your funds[1].
> 
> We're very sorry that we have to turn away your business, and wish you the best of luck moving forward.
> 
> Best,
> Aideen
> 
> [1] https://dashboard.stripe.com/transfers <https://dashboard.stripe.com/transfers>
Graham Hines 
Dee View Road
Connah’s Quay
Flintshire
CH5 4AY

07903 268439
grahamhines1@icloud.com

**Comment by yuzoolcode** [comment]
Thanks for letting me know Graham - and good luck with the Store!
