### ISSUE TITLE
Locked Bug

### ISSUE THREAD

**Issue by iJasonWade** [yuzoolcode/yuzoolthemes-tracking#17]
I purchased the Locked stack and after adding it to a new page and without modifying it I get the following error while trying to preview the page:

![Screen Shot 2019-03-15 at 9 24 19 AM](https://user-images.githubusercontent.com/12824479/54438594-f1949a80-4704-11e9-904f-89dba6a4949f.png)

**Comment by yuzoolcode** [comment]
Not sure what that is... I just opened the demo RW project with Locked and can see it in preview mode:

![RapidWeaver 2019-03-16 at 21 21 11](https://user-images.githubusercontent.com/4608547/54475165-72e94b80-4831-11e9-877b-7f3af295c3f8.jpg)

- Can you see like this with the RW test project?
- Is the error after you add a new Locked to the page?
- Have you added or changed any of the default options?

Thanks

**Comment by iJasonWade** [comment]
It works in the example project you provide, I get the error when I create a new page in my existing website and add Locked to it without changing any of the default options. The only thing I can think of that might be causing a conflict is that I use the Splash Theme from 1LD, https://onelittledesigner.com/rapidweaver-theme/splash/

**Comment by yuzoolcode** [comment]
- I unfortunately don't have that theme so can't test :(
- Do you have a demo page you can publish too?
- Or better, can you export the site to your desktop and ZIP it and add it to the comments here and I will test the exported code
- Of course it will work if you try it in another theme so it must be some weird clash ..
- Do you have any other Stacks on the page? Try it with only Locked and Splash theme

**Comment by iJasonWade** [comment]
Sorry for the slow response, I will export the site for you, for the locked page the only other stack was an image

**Comment by yuzoolcode** [comment]
Thanks - please export and add it here ;) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yuzoolcode** [comment]
Any update on this?
