### ISSUE TITLE
Stripe Stack Stopped Working

### ISSUE THREAD

**Issue by MoSohi** [yuzoolcode/yuzoolthemes-tracking#18]
I see you've closed the previous case for this Stripe Stack stopped working.
But problem still there.
Mine was working 6-7 days ago, but now it says:
THE STRIPE TOKEN WAS NOT GENERATED CORRECTLY
I double checked everything and there was no changes from my part in my website.
Please advise.
![Screen Shot 2019-03-16 at 21 21 48](https://user-images.githubusercontent.com/48636132/54483979-7bdb1c80-4833-11e9-86f9-de2e1f750866.png)

**Comment by yuzoolcode** [comment]
This one?
https://github.com/yuzoolcode/yuzoolthemes-tracking/issues/16

Yes because it was a different issue

**Comment by yuzoolcode** [comment]
This is not a bug but most likely some incorrect setting
You can see it's still working on the live demo (and just tried it in RW8):
http://demo.yuzoolthemes.com/stripe/

> Mine was working 6-7 days ago, but now it says:
> THE STRIPE TOKEN WAS NOT GENERATED CORRECTLY
> I double checked everything and there was no changes from my part in my website.

Things to consider:

- Do you have a link to your site?
- Are your keys inserted correctly and without spaces before and after?
- Can you try a demo test keys and publish to a demo page and that works? 
- Something must have changed... did you update anything else on the site or republish from RW?

**Comment by MoSohi** [comment]
Yes #16
It was the exact same issue.
You see graham57 said: "a client said she could not use it and trying it today neither could I. She successfully paid me about 3 weeks ago using it."
and if you see his last reply he said: "guess I’ll use PayPal!" That shows he gave up on resolving this issue.
There is a possibility for a bug, I got payment went through some days ago but can't get payment anymore. I already sent you the error.
Have you tried to charge yourself for a real test?

**Comment by MoSohi** [comment]
What happened to this inquiry?
As I mentioned before, I checked everything is correct, and my site was working properly in last 2 weeks. Nothing happened from my part, your checkout stack does not work with Stripe anymore.
Please do something as my business is interrupted.

**Comment by yuzoolcode** [comment]
Sorry I thought you were talking about Stripe Stack as it says in your message title.

Also that other user on #16 is referring to something else.
If you read the full message, he says politely that he can no longer use the Stripe component as Stripe didn’t allow his product to be sold through them, so he must use PayPal (against Stripe Terms). Please re-read it.

I can’t help you further if you don’t supply anymore information such as a link or anything else.

As it happens this isn’t a bug but most likely you don’t have the latest version.

Stripe permissions were improved for the latest version of Checkout Stack as mentioned here;
https://updates.yuzoolthemes.com/post/183263854077/checkout-stack-106

You must have already received an email and can update via the RW settings.

Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
