### ISSUE TITLE
WALL STACK NOT WORKING WITH FOUNDRY

### ISSUE THREAD

**Issue by Figory** [yuzoolcode/yuzoolthemes-tracking#19]
Wall stack creates huge blank space below news feed in Foundry.

Foundrey developer said the following
My guess is that he needs jQuery v3.3.1 for his stack, which he's including in the stack itself, and the Foundry is loading its own jQuery version, which is coming directly from the Stacks plugin, that I load at the bottom of the page. Mine is overriding his likely and if he needs v.3.3.1 then that is a problem.

**Comment by yuzoolcode** [comment]
Thanks @Figory but don’t worry that’s not the issue.

I’ve seen this before. Assuming your Wall Stack is working then the space at the bottom is I thin a CSS issue.

This has been reported before. Please check the closed issues on here or under yuzoolthemes.com/faqs/ and search the Disqus comments and the solution was posted on there somewhere...

Failing that - can you post your URL here and can see if can see the issue.

Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yuzoolcode** [comment]
I can’t find any notes on it on those areas - searching the RW forums might have it

If not, let’s go off the link!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yuzoolcode** [comment]
Please let me know on this and will get a fix out for Wall + Foundry shortly 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Figory** [comment]
Thanks so much.

No sorry I dont know if I'm being half witted, but I can't find anyone having the same problem on any forum.

It is here on my test site home page http://wylieweb.com <http://wylieweb.com/>

Password 1234

THANK YOU!

**Comment by Figory** [comment]
Hi I have made a page here with just a WALL stack as I need to move the WALL from home page until I get it working

https://wylieweb.com/news/

THANKS

**Comment by Figory** [comment]
Hi

Im sorry I have had to move on, the client approved a twitter feed embed widget.

Can I get a refund for wall?  
Usually I wouldn't ask, but this one was expensive and im fairly skint, and unlikely to need the stack for anyone else.

Thanks

**Comment by Figory** [comment]
Hi

Im sorry I have had to move on, the client approved a twitter feed embed widget.

Can I get a refund for wall?  
Usually I wouldn't ask, but this one was expensive and im fairly skint, and unlikely to need the stack for anyone else.

Thanks

**Comment by yuzoolcode** [comment]
![CleanShot 2019-03-31 at 14 33 17](https://user-images.githubusercontent.com/4608547/55285281-7b11c100-53c3-11e9-9100-028a41476e3f.jpg)

It didn't need a fix - just add the "jquery" option in the Stack and it works in Foundry - so there was never an issue I'm afraid :(
