### ISSUE TITLE
Purchasing problem

### ISSUE THREAD

**Issue by rap2000us** [yuzoolcode/yuzoolthemes-tracking#2]
My bank will not let me purchase from outside the US (to protect me!!) and I need to ask them to unlock the account and tell them which country I want to purchase from and an amount for the purchase.  It may seem like a small thing but I cannot find where yazoolthemes is located or where the merchant processor is located so that I can authorize a purchase.  Many times I just make the purchase from a personal account instead of my business account but I would really like to make this purchase the right way.  Cal you help?

**Comment by yuzoolcode** [comment]
Sure :)

Do you usually purchase via credit card?
If so, you can tell them US + USD as it's processed via Stripe (https://stripe.com)

Anymore problems please send a quick email / note here:
https://www.yuzoolthemes.com/support.html

Really hope it works out and let us know if anything else needed :)
