### ISSUE TITLE
Account deleted

### ISSUE THREAD

**Issue by SHWray** [yuzoolcode/yuzoolthemes-tracking#20]
Hi Michael

I've been away and seen I've missed your email about non payment on the Writer account. It went into spam, My payment card has expired. Could you arrange to reinstate the account and I will make the $8 payment so that I have more time to collate the existing content and transfer to another system.

Thanks

Simon

**Comment by yuzoolcode** [comment]
Thanks Simon - can do that but will have to wait about 1 week. Will email you once it’s back online. Sorry if you didn’t see the emails.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SHWray** [comment]
Thank you

**Comment by yuzoolcode** [comment]
Will update you on this today

**Comment by yuzoolcode** [comment]
Done and sent this to you :)
