### ISSUE TITLE
Just Forms not emailing me submission notifications

### ISSUE THREAD

**Issue by iamhoffer** [yuzoolcode/yuzoolthemes-tracking#21]
Hi, I am making few forms for my web page but for whatever reason, I can not get the submitted forms notification sent to my email inbox. In the notification section I put in the Recipient Email address and I also set up to receive a cc copy and a bcc copy. The issue is I am not getting the notifications in my inbox.

**Comment by yuzoolcode** [comment]
Just replied to your comment on Facebook...
