### ISSUE TITLE
submit does not work if a required element is left blank by a rule

### ISSUE THREAD

**Issue by kappalab** [yuzoolcode/yuzoolthemes-tracking#22]
Suppose I have a conditional rule to show/hide an element which is "required", when the conditional rule hides the element (i.e., the element is left blank) in the new JustForm, the Submit button does not work at all.

**Comment by yuzoolcode** [comment]
- is there an error message when trying to submit? e.g. "all required fields.."
- do you have a link to your form?

Cheers

**Comment by kappalab** [comment]
>   * is there an error message when trying to submit? e.g. "all required
>     fields.."

No, there is no error. Clicking "Submit" does not do anything.

>   * do you have a link to your form?

I have a form you can test at
https://forms.justdropkick.com/app/form?id=107

Just click the Next on the first page, and then click Submit with the "first" menu item selected to find there is nothing happens.

If you choose the "second" menu item and enter something in the conditional field, then Submit will work.

If you leave the field blank, it will bring up a warning, by the way.

**Comment by yuzoolcode** [comment]
- One solution would be to make the "以前の注文のライセンス番号" non-required

- Another solution is to maybe make the "first" option "skip" the next input field?
Option settings are like this:


![CleanShot 2019-04-28 at 20 31 33](https://user-images.githubusercontent.com/4608547/56863766-5a09b380-69f5-11e9-8821-4eaf7aa25615.jpg)

**Comment by kappalab** [comment]
"Skip" seems still requiring the filed entry if the field is "required". It looks like making the field non-required is the only viable solution at this moment which does not work for me (I cannot let the filed left blank). So, I hope it can be improved soon.

**Comment by yuzoolcode** [comment]
We're working on a few other updates today so will try and factor this in also. Please check back on your form tomorrow to see if it has improved to how you wish.

If we can't add it at this time, we will in the near future. In the meantime making it non-required but adding a placeholder note "please fill this in" or something similar should surely help.

Thanks for your feedback

**Comment by kappalab** [comment]
Just checking if you have deployed the updates yet since I see no changes so far.

**Comment by yuzoolcode** [comment]
Yes we made some improvements to the rules. But for your case, please make it non-required but adding a placeholder note "please fill this in" or something similar for the meantime. Or have options available without using the rules.

**Comment by kappalab** [comment]
Thank you very much and I hope the improvement will be implemented soon :)
