### ISSUE TITLE
Cart2

### ISSUE THREAD

**Issue by kwstevens** [yuzoolcode/yuzoolthemes-tracking#23]
Hi - I have Cart2 working on my site with Desktops & iPad - but it doesn't work on iPhone.
It's enabled for all devices. Any suggestions on best way to fix? - Page in question:

https://www.hdstherapy.com/Other-Services-Psychotherapist-Berkshire/training_courses/index.php

Thanks

**Comment by kwstevens** [comment]
Sorry,  Found the problem. Time for me to upgrade my old iPhone!!
All works perfectly on a modern, up to date iPhone - can't believe how quickly gadgets go out of date.

Sorry for posting before engaging brain.......
K

**Comment by yuzoolcode** [comment]
No worries - glad you found the solution 🤩

Should work on iPhone 6 and above 👍
