### ISSUE TITLE
Just Forms

### ISSUE THREAD

**Issue by Lambrechts-R** [yuzoolcode/yuzoolthemes-tracking#24]
I used Just forms for a few weeks ... and everthing works fine ..... till yesterday. When the form is filled in and send, nothing ! There's no mail send or received. I didn't change anything on the webpages, so I suppose there no error on my side. When I bought the stack, I recieved a license key. Is there a place where I have to fill it in.

**Comment by yuzoolcode** [comment]
Thanks @Lambrechts-R 

Strange that it would stop working as you say! 

Let's try:

- according to the logs the email notifications are working
- what form are you referring to? I can do a look up of the notifications for that form and see where they are going
- did you also check the junk/spam just in case?

**Comment by Lambrechts-R** [comment]
Hi,

yes indeed, very strange.  It went well (sending and receiving in my mailbox) till yesterday.  When I send a form it shows in the DB, so that’s good, but I don’t receive any notifications i my mailbox.

There are messages in my spam.

this is one off the forms : https://forms.justdropkick.com/app/form?id=93 <https://forms.justdropkick.com/app/form?id=93>   

Thanks

--------------------------------
Rudy Lambrechts
rudylambrechts@icloud.com
————————————————

**Comment by yuzoolcode** [comment]
Thanks 

- I just did a test entry and you should have it :) 
- Just in case, please move mails from Spam to your inbox to "whitelist" them

This should be working going forward.
Let me know if anymore issues!

Thanks

**Comment by Lambrechts-R** [comment]
Hi Michael, thanks ... but I noticed another problem. The confirmation mails don't work! I receive a notification in my mailbox, but when I test the conformation .... no answer (spam is empty to). Can you assist me?

--------------------------------
Rudy Lambrechts
rudylambrechts@icloud.com
————————————————

**Comment by yuzoolcode** [comment]
Looking at the server logs @Lambrechts-R  - the confirmation emails are going out on all the forms.

I can see some being blocked on your form though. Those are ones for @icloud or @me address. If you test with another address not on that server you should see the confirmation.

That server was accepting emails the day before so it could be just the server was down rather than something more serious? 

Please let me know

**Comment by Lambrechts-R** [comment]
Hi Michael, after a few months with no problems ... it happens again, I don't receive any notification in my mailbox.  Can you please help me !
