### ISSUE TITLE
YouTube videos are not displaying in the Video stack

### ISSUE THREAD

**Issue by acpodz** [yuzoolcode/yuzoolthemes-tracking#26]
Hi,
YouTube videos used to display OK in the Video stack but no longer do. This is what is displayed on the web page:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/51298237/58765891-3ac3f000-8578-11e9-88f0-b8a32fbaacb0.png">
This is the setup:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/51298237/58765903-5cbd7280-8578-11e9-9956-0a43df4f7f91.png">

**Comment by yuzoolcode** [comment]
It's working:

![CleanShot 2019-06-03 at 08 45 17](https://user-images.githubusercontent.com/4608547/58768848-fa965900-85db-11e9-8bbb-861b3029db4c.jpg)

You need to use the "watch" share URL and not the short URL

e.g.
https://www.youtube.com/watch?v=gQ9ZVGM7smE

![CleanShot 2019-06-03 at 08 46 11](https://user-images.githubusercontent.com/4608547/58768858-0eda5600-85dc-11e9-87c2-29d44b168064.jpg)

Please use that version of the URL

**Comment by acpodz** [comment]
Many thanks for the quick reply. As you wrote, it works!

Regards
Andrew
