### ISSUE TITLE
Index.html files in the Kiki theme

### ISSUE THREAD

**Issue by Fotobodyart** [yuzoolcode/yuzoolthemes-tracking#3]
I use the KiKi theme in rapidweaver 8.
Under Advanced the last option is to tidy the web links (delete the index.html)
I have checked this option.
But when I look in the sitemap, the index.html file still exists everywhere, this for instance gives problems with Google Search.
Best Regards,
Jaap
[sitemap.rtfd.zip](https://github.com/yuzoolcode/yuzoolthemes-tracking/files/2385413/sitemap.rtfd.zip)

**Comment by yuzoolcode** [comment]
Thanks @Fotobodyart for reporting the bug.

Is this just for Kiki theme? E.g. if you do the same for other themes in RapidWeaver 8 does it work correctly?

**Comment by Fotobodyart** [comment]
Thanks for the answer.

I also have anther site with the theme Reason and there i have the same problem.
Because i am very busy with my page in Kiki i didn’t notice that Reason also has this problem.

**Comment by yuzoolcode** [comment]
Great - thanks for testing that.

I guess we need to alert Realmac about this and hope a fix is added to RW8 in an update
