### ISSUE TITLE
Locked logout issue

### ISSUE THREAD

**Issue by quietchat** [yuzoolcode/yuzoolthemes-tracking#31]
In Rapidweaver, when I create a button with a link "?logout" for the Locked stack, I'm dropped back to the login page.  All good.  If I add "?logout",(minus quotes), to redirect to the home page, Locked no longer protects the pages where I have placed the Locked stack.  I've tried various permutations--page name only, fully qualified URL, with slash and without,  moving the stack on the page.  All result in the same problem.  Any thoughts?

**Comment by yuzoolcode** [comment]
- do those other pages that are no longer locked have the Locked Stack on them?
- do you have a demo URL?
- it could be they are protected but the cache is not being cleared

For the demo this is how I did a log out:

http://demo.yuzoolthemes.com/locked/
password "demo"
Log Out button is in the body

**Comment by quietchat** [comment]
Thanks for the quick reply.

1. There are four pages which are locked and have the Locked Stack with the same password assigned.
2. Here is the live site with sensitive information blocked: pmahweb.org/vol_section <http://pmahweb.org/vol_section>. The password is wiffle1.
3. You have to be using either cookies or session management.  From your question I take it you are using cookies.  I'm not sure how I can force cache to be cleared.  Meta tags are iffy at best.  Is there some neat way to do that?  I can think of a half dozen ways to use it if there is.

Thanks again for the quick reply, I really appreciate it.

Brian

**Comment by yuzoolcode** [comment]
No worries Brian - I think I can see what is happening and it might be because the docs are not clear enough.

- The user is not being logged out by your Logout buttons so still logged in
- reason is because need to add the "?logout" to the current URL
- e.g. https://pmahweb.org/vol_section/Roster/index.php?logout
and not https://pmahweb.org/?logout (as that page doesn't have the logout Stack on it)

Please try that and let me know!

**Comment by quietchat** [comment]
Yup.  That works.  In fact, just a simple  "?logout"  does the job.  The documentation led me to believe that I could log out and redirect to an unprotected page.  That would be a nice feature, but I now understand how the stack actually works and see why that is impractical.  

Perhaps sometime in the future you might add a drops zone for a nav bar to the login page to allow the user to get back to the unprotected section of the site after logging out rather than have to re-enter the url.  

Anyway, I thank you for the clarification. Your stacks are excellent and I look forward to seeing more of them.

Brian

**Comment by yuzoolcode** [comment]
Thanks Brian - really appreciate that nice feedback :) 

That's a good suggestion and will bear in mind for a future update!
