### ISSUE TITLE
Looking at the server logs @Lambrechts-R  - the confirmation emails are going out on all the forms.

### ISSUE THREAD

**Issue by Lambrechts-R** [yuzoolcode/yuzoolthemes-tracking#35]
Hi Michael, after a few months with no problems ... it happens again, I don't receive any notification in my mailbox. Can you please help me !

-----

Looking at the server logs @Lambrechts-R  - the confirmation emails are going out on all the forms.

I can see some being blocked on your form though. Those are ones for @icloud or @me address. If you test with another address not on that server you should see the confirmation.

That server was accepting emails the day before so it could be just the server was down rather than something more serious? 

Please let me know

_Originally posted by @yuzoolcode in https://github.com/yuzoolcode/yuzoolthemes-tracking/issues/24#issuecomment-491675029_

**Comment by Lambrechts-R** [comment]
Hi,
I send you several messages concerning the issue I have with Just Forms.  Support is really needed !  Can you please help me.

**Comment by yuzoolcode** [comment]
https://github.com/yuzoolcode/yuzoolthemes-tracking/issues/38#issuecomment-516637019
Should all be back now
