### ISSUE TITLE
Alt Attribute For Logo Image In Navigation 

### ISSUE THREAD

**Issue by csmltd** [yuzoolcode/yuzoolthemes-tracking#36]
I have noted via a number of SEO reports that the Logo I use within Navigation stack does not have an alt attribute attached to it.

Having checked the Navigation I cannot see how I can add the alt attribute to my warehoused logo image.

I’m sure there is a quick fix or some code that can be added but I need your help to resolve this.

Thanks in advance.

Kind Regards
Paul

**Comment by csmltd** [comment]
Any chance of a response??

Paul

**Comment by yuzoolcode** [comment]
Thanks @csmltd Paul it's not a quick fix I'm afraid.. will have to look at how to add this in a future update

It takes the Logo from RW so will try and set it to take the ALT if possible

**Comment by csmltd** [comment]
Given that it took you 3 weeks to even respond after repeated requests I always knew it would never be a 'quick fix'.

It would be wrong of me to say that I will become a loyal supporter of Yuzool stacks - which saddens me as technically you have a lot to offer - however this always needs to be backed up by efficient and responsive support - in this department Yuzool simply doesn't make the grade.

**Comment by yuzoolcode** [comment]
I'm sorry you feel that way. But unfortunately my life got in the way and that's more important to me than an ALT tag

Good luck with the projects
