### ISSUE TITLE
JustForms stopped sending out notifications

### ISSUE THREAD

**Issue by kappalab** [yuzoolcode/yuzoolthemes-tracking#37]
Last week, my form stopped sending out notifications e-mails. Until then, it worked fine and I did not change notifications settings at all. Do you think you can look into the issue for me?

**Comment by Lambrechts-R** [comment]
I have the same problem ..... I have already sent several emails to the developer, but no answer !

**Comment by Lambrechts-R** [comment]
10 days .... no answer.  Is there another way to contact the developer ?

**Comment by kappalab** [comment]
Only thing I can think of is https://www.yuzoolthemes.com/faqs/, but the questions have not been responded last 2 weeks either. I hope they will come back eventually.

**Comment by yuzoolcode** [comment]
Sorry I had a few health issues past couple weeks.. 
But all should be back
