### ISSUE TITLE
Backup Frank / RapidWeaver error

### ISSUE THREAD

**Issue by MarceloLang** [yuzoolcode/yuzoolthemes-tracking#4]
nothing works! PHP error!
Video-Link: [www.youtu.be/JKB03S1K5As](https://youtu.be/JKB03S1K5As)

**Comment by yuzoolcode** [comment]
Can you send me your project?
Thanks

**Comment by yuzoolcode** [comment]
It might be the server .. also include your server information, thanks

**Comment by MarceloLang** [comment]
RW-Project-Link: http://pc.cd/WyH7
I do not think the problem is my server setting
I think you just offer the wrong file for download ;-) 🥇

**Comment by yuzoolcode** [comment]
Thanks for this bug report :)

Made the distribution file fix and also made the preview screen better!

![2018-10-02 at 11 09](https://user-images.githubusercontent.com/4608547/46325550-bc532f00-c633-11e8-923c-c99929d7eb79.jpg)

**Comment by yuzoolcode** [comment]
This will be ready to download in about 1 hour 👍

**Comment by yuzoolcode** [comment]
![2018-10-02 at 11 10](https://user-images.githubusercontent.com/4608547/46325588-f7556280-c633-11e8-93b4-2c3a2f3dd4ef.jpg)

Publish mode
