### ISSUE TITLE
Messenger Stack: Z-Index Issue

### ISSUE THREAD

**Issue by brijazz** [yuzoolcode/yuzoolthemes-tracking#5]
There appears to be a z-index issue with your Messenger stack.  I have it's z-index set to 99999, but upon publishing the z-index is actually being set to 1, as you can see in the attached screenshot.  This is causing issues with the Messenger stack being covered by other stacks with indexes > 1.
<img width="970" alt="yuzool" src="https://user-images.githubusercontent.com/10696709/48498191-aeccbf80-e803-11e8-8baa-6992d76956e4.png">

**Comment by yuzoolcode** [comment]
![2018-11-15 at 21 01](https://user-images.githubusercontent.com/4608547/48551759-cdbd7580-e919-11e8-807e-e5fe0ffb06e1.jpg)

Have just tested and it seems fine.

Can you supply a link to check? Thanks

**Comment by brijazz** [comment]
Sure.  Site in development is at https://dev.keynotemusicstudio.ca, and if you’d like to see my RW file it can be found at https://dev.keynotemusicstudio.ca/kms.zip

Thanks!

**Comment by yuzoolcode** [comment]
Great - confirmed

Pushing an update now:
- Z-Index limit extended to Button 

Should be ready in about 15 mins from within the app and you'll get an email :) 

Thanks

**Comment by brijazz** [comment]
Hey, that’s great! Thanks for the quick fix, I appreciate it.  However… I’m having an issue installing the update for some reason. I saw that version 1.1.3 is available in the Stacks update and installed it.  But when I restart RW, I’m still on 1.1.2 and the update still shows as being available (as opposed to installed).  Weird stuff, and reproducible… I’ve attached a screencast to prove that I’m not a crazy person!

Thx,
Brian

**Comment by yuzoolcode** [comment]
Hmmm strange…
Try the version emailed also. Drag that onto the RW icon and reset RW

**Comment by brijazz** [comment]
Sorry, not seeing any attachment.

**Comment by brijazz** [comment]
Got the email, downloaded 1.1.3 and installed it successfully.  Z-index issues resolved!  Thanks again for all of your help with solving this issue.

**Comment by yuzoolcode** [comment]
Thank you @brijazz  for your patience and working with me on this :)
