### ISSUE TITLE
3D Card Stack Adjustments

### ISSUE THREAD

**Issue by design4film** [yuzoolcode/yuzoolthemes-tracking#6]
Could you explain how I can change or rotate the direction, angle or perspective of the cards in the ‘Card’ stack?

I’m hoping to adjust the card placement on the page (in the stack container), rather than adjusting the image on the card.

Please advise. Thank you.

**Comment by yuzoolcode** [comment]
![2018-11-19 at 10 35](https://user-images.githubusercontent.com/4608547/48681612-e2825d80-ebe6-11e8-9868-bd9b31582a3f.jpg)

These are the kind of options per card.

What are you trying to achieve specifically? Do you have a link?

Perspective is not an option but you can change the direction in the dropdown options
