### ISSUE TITLE
Checkout stack refusing to update to 1.0.5

### ISSUE THREAD

**Issue by mp1963** [yuzoolcode/yuzoolthemes-tracking#8]
I have RW 8 (Version 8.0.3 (20142)). I currently see that Checkout 1.0.3 is installed. Every time I open a project in RW the Checkout stack tries to update to 1.0.5 but this process fails without generating any error, the Checkout version remains at 1.0.3

I have tried reinstalling the stack but this makes no difference.

**Comment by yuzoolcode** [comment]
Sorry about this... let me check

**Comment by yuzoolcode** [comment]
Please try again @mp1963  -  you might need to restart RW but it should be working now for sure :)

**Comment by mp1963** [comment]
Problem resolved. Thank you very much.

**Comment by llangpierce** [comment]
I am having the same issue with 106
<img width="637" alt="Screen Shot 2019-05-06 at 10 45 24 AM" src="https://user-images.githubusercontent.com/50337283/57244217-cc2d5a00-6fec-11e9-986b-1e624698e045.png">

**Comment by yuzoolcode** [comment]
The server might be down @llangpierce - so try again today and see.. let me know

Alternatively, download again from the original email link.

**Comment by llangpierce** [comment]
This has been happening for a couple of months. I cannot find the email anywhere is there another way to verify?
Thanks
Linda

`·.¸¸ ><((((º>.·´¯`·><((((º>
><((((º> ·...><((((º>
·...><((((º>

Linda Lang Pierce
linda@langpierce.net

www.langpierce.net

949•230•7205

**Comment by yuzoolcode** [comment]
- please try it again in the app
- if it doesn't work, I've sent you a direct download link by email :)

**Comment by yuzoolcode** [comment]
Hopefully you got this now :)

**Comment by llangpierce** [comment]
Thank you! Yes it is working perfectly!

`·.¸¸ ><((((º>.·´¯`·><((((º>
><((((º> ·...><((((º>
·...><((((º>

Linda Lang Pierce
linda@langpierce.net

www.langpierce.net

949•230•7205

**Comment by Lambrechts-R** [comment]
Hi,

A problem with Just Forms … a few months ago I noticed a problem : the confirmation mail doesn’t arrive in my mailbox.  Until yesterday everything worked well, but since today I have the same problem.  Can you assist me ?

--------------------------------
Rudy Lambrechts
rudylambrechts@icloud.com
————————————————



> Op 8 mei 2019, om 17:39 heeft llangpierce <notifications@github.com> het volgende geschreven:
> 
> Thank you! Yes it is working perfectly!
> 
> `·.¸¸ ><((((º>.·´¯`·><((((º>
> ><((((º> ·...><((((º>
> ·...><((((º>
> 
> Linda Lang Pierce
> linda@langpierce.net
> 
> www.langpierce.net
> 
> 949•230•7205
> 
>
